### ISSUE TITLE
What is this plugin for?

### ISSUE THREAD

**Issue by BarbzYHOOL** [eth-p/fish-plugin-sudo#1]
Hello,

What does it do?

**Comment by typecasto** [comment]
I'm wondering as well. Some screenshots would be nice.

**Comment by eth-p** [comment]
I managed to miss seeing this issue entirely, sorry. I just updated the repo to explain what it the plugin actually does.

**Comment by typecasto** [comment]
Isn't the second part of that (the ctrl+s) handled by fish itself through the shortcut alt+s? Or does this plugin handle it differently?
